# Site settings
title: Belajar Linux
email: 
description: > # this means to ignore newlines until "baseurl:"
  Belajar Terminal Linux pada materi sistem operasi berbasis text.
baseurl: "/belajar-linux" # the subpath of your site, e.g. /blog/
url: "http://saifulindo.github.io" # the base hostname & protocol for your site
twitter_username: saifulindo
github_username: saifulindo

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
